### ISSUE TITLE
Can this work with nvim

### ISSUE THREAD

**Issue by CapelaGames** [shader-ls/shader-language-server#1]
Hi, 
If it is possible, I would love some help to get this working with nvim. I've been reading a lot of documentation and I can't see to work it out.

I am not sure if you can help with this, but I thought I would ask.

Thanks

**Comment by jcs090218** [comment]
Yes, this can work with nvim; it should work with any editor. However, I don't have enough experience to contribute to nvim. Maybe open an issue to https://github.com/neovim/nvim-lspconfig/issues would help? 🤔

**Comment by CapelaGames** [comment]
Thank you, I will give that a go.

**Comment by HenrysHouses** [comment]
i couldnt find any issue related to this on the nvim-lspconfig repo nor is this lsp included there yet, but i have it working in my config at least. its a fairly simple setup. although im having to use a secondary lsp for diagnostics as this one doesnt have that yet. so im using one lsp for hlsl, and this for shaderlab. just make sure you download the shader-ls with the dotnet cli and this should work out of the box like so:

~/.config/nvim/lua/configs/lspconfig.lua
```lua
-- vim does not have a definition for these file types by default, so we define them manually. the naming here can be whatever but this works fine.
vim.filetype.add({
	extension = {
		shader = "hlsl",
		cginc = "hlsl",
		glslinc = "hlsl",
		compute = "hlsl",
		cg = "hlsl",
		hlsl = "hlsl",
	},
})

-- Unity shaderlab support
vim.lsp.config("ShaderLab_ls", {
	cmd = {
		"shader-ls",
		"--logLevel",
		"Information",
		"--stdio",
	},
	filetypes = { "shader", "cginc", "glslinc", "compute", "cg", "hlsl" },
	root_markers = {
		".git",
		".csproj",
		".sln",
	},
})
vim.lsp.enable("ShaderLab_ls")
```

~/.config/nvim/lua/plugins/lsp.lua
```lua
return {
  {
    "neovim/nvim-lspconfig",
    config = function()
      require "configs.lspconfig"
    end,
  },
}
```
